### ISSUE TITLE
The app crashes when rendering URL using CSSBox

### ISSUE THREAD

**Issue by SuperMartas** [FitLayout/FitLayout#5]
When I enter URL https://supermartas.cz/ on https://layout.fit.vutbr.cz/ and select CSSBox as a renderer, the app crashes with `NullPointerException`, see image:
![image](https://user-images.githubusercontent.com/7558984/151410626-2f5eae87-24b5-419f-994f-2a110cc91f99.png)

The same behavior can be reproduced from code:
```java
var renderer = new CSSBoxTreeProvider("https://supermartas.cz/", 1920, 1080);
renderer.getPage();
```

**Thrown exception:**
```
java.lang.NullPointerException: Cannot read field "left" because "this.emargin" is null
	at org.fit.cssbox.layout.ElementBox.getAbsoluteContentX(ElementBox.java:824)
	at org.fit.cssbox.layout.Box.getAbsoluteContentBounds(Box.java:633)
	at org.fit.cssbox.layout.BlockBox.updateStaticPosition(BlockBox.java:1486)
	at org.fit.cssbox.layout.BlockBox.absolutePositions(BlockBox.java:1395)
	at org.fit.cssbox.layout.Viewport.absolutePositionsChildren(Viewport.java:409)
	at org.fit.cssbox.layout.Viewport.updateBounds(Viewport.java:344)
	at org.fit.cssbox.layout.Engine.createLayout(Engine.java:225)
	at cz.vutbr.fit.layout.cssbox.impl.CSSBoxTreeBuilder.renderUrl(CSSBoxTreeBuilder.java:290)
	at cz.vutbr.fit.layout.cssbox.impl.CSSBoxTreeBuilder.parse(CSSBoxTreeBuilder.java:139)
	at cz.vutbr.fit.layout.cssbox.impl.CSSBoxTreeBuilder.parse(CSSBoxTreeBuilder.java:217)
	at cz.vutbr.fit.layout.cssbox.CSSBoxTreeProvider.getPage(CSSBoxTreeProvider.java:212)
```

**Expected behavior:**
The page is rendered without error/exception as it does for example for URL http://cssbox.sf.net/.

**Comment by radkovo** [comment]
This seems to be a CSSBox issue, most probably related to radkovo/CSSBox#60. I will check that. In general, CSSBox is suitable for simple pages only, Puppeteer should be preferred.
